### ISSUE TITLE
Error on install or build from source

### ISSUE THREAD

**Issue by Lewiscowles1986** [cogitatio/vagrant-hostsupdater#112]
Hi,

I've tried googling this, it's really annoying as I've not had many problems with this plugin before...

```
Installing the 'vagrant-hostsupdater-1.0.2.gem' plugin. This can take a few minutes...
/usr/lib/ruby/2.3.0/rubygems/specification.rb:946:in `all=': undefined method `group_by' for nil:NilClass (NoMethodError)
    from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:275:in `with_isolated_gem'
    from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:131:in `install_local'
    from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:47:in `install_plugin'
    from /usr/share/vagrant/plugins/commands/plugin/action/install_gem.rb:37:in `call'
    from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
    from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
    from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
    from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
    from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
    from /usr/share/vagrant/plugins/commands/plugin/command/base.rb:14:in `action'
    from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:32:in `block in execute'
    from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `each'
    from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `execute'
    from /usr/share/vagrant/plugins/commands/plugin/command/root.rb:56:in `execute'
    from /usr/lib/ruby/vendor_ruby/vagrant/cli.rb:42:in `execute'
    from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:268:in `cli'
    from /usr/bin/vagrant:173:in `<main>'
```

Would this happen to be a problem with Ubuntu?

It's 16.04 64-bit, stock vagrant, stock ruby

**Comment by Lewiscowles1986** [comment]
:wink: Fixed as per

http://stackoverflow.com/questions/36811863/cant-install-vagrant-plugins-in-ubuntu-16-04

**Comment by cgsmith** [comment]
Thanks for the update @Lewiscowles1986
